import type { Metadata } from "next";
import { CaseStudyShell } from "@/components/SiteShell";

export const metadata: Metadata = { title: "Microsoft Sentinel SOC & Threat Detection", description: "Hands-on Microsoft Sentinel case study covering Entra ID telemetry, KQL detection engineering, incident investigation, evidence standards and controlled validation." };

export default function AzureSocLab() {
  return <CaseStudyShell><main><section className="case-hero section-dark"><div className="container case-hero-grid"><div><p className="eyebrow">CASE STUDY 01 • INDEPENDENT SECURITY LAB</p><h1>Microsoft Sentinel SOC & Threat Detection</h1><p>A hands-on detection-engineering and incident-response lab focused on Microsoft Entra ID sign-in telemetry, KQL analytics, Sentinel investigation workflows and evidence-led validation.</p><div className="case-cta"><a className="button button-primary" href="https://github.com/KaffyDevelops/azure-soc-lab" target="_blank" rel="noreferrer">View GitHub repository ↗</a></div></div><aside className="case-facts"><div><small>FOCUS</small><strong>Detection & Response</strong></div><div><small>PLATFORM</small><strong>Microsoft Azure</strong></div><div><small>TOOLS</small><strong>Sentinel • Entra ID • KQL</strong></div><div><small>STATUS</small><strong>Detection implemented • incident validation in progress</strong></div></aside></div></section><section className="case-body"><div className="container case-layout"><nav className="case-nav"><a href="#context">Context</a><a href="#detection">Detection</a><a href="#investigation">Investigation</a><a href="#quality">Quality</a><a href="#validation">Validation</a><a href="#lessons">Lessons</a></nav><article className="case-content"><section id="context" className="case-section"><p className="eyebrow dark">CONTEXT</p><h2>Practise the work behind a SOC alert, not just the interface.</h2><p>The project is designed around the full analyst chain: useful identity telemetry, a documented detection hypothesis, query execution, alert/incident generation, investigation, false-positive analysis, response guidance and a defensible evidence record.</p><div className="case-note">This is an independent hands-on lab. It is not presented as employment experience.</div></section><section id="detection" className="case-section"><p className="eyebrow dark">DET-001</p><h2>Repeated failed Microsoft Entra ID sign-ins.</h2><p>The current implemented detection identifies more than five invalid-password events grouped by source IP and user principal name. Its documentation includes the threat hypothesis, SigninLogs data source, MITRE ATT&CK mapping to T1110 Brute Force, analyst triage questions, false-positive considerations, response guidance and production limitations.</p><div className="code-block">{`SigninLogs
| where ResultType == "50126"
| summarize FailedAttempts = count() by IPAddress, UserPrincipalName
| where FailedAttempts > 5
| project IPAddress, UserPrincipalName, FailedAttempts
| order by FailedAttempts desc`}</div></section><section id="investigation" className="case-section"><p className="eyebrow dark">INCIDENT INVESTIGATION</p><h2>Turn a matched threshold into an analyst decision.</h2><p>The repository now includes an INC-001 runbook and investigation queries for failure confirmation, chronological sign-in timeline, success-after-failure correlation, same-source cross-user activity and DET-001 validation.</p><p>The incident record defines the hypothesis, expected result, evidence requirements and final-disposition logic before tenant evidence is collected.</p></section><section id="quality" className="case-section"><p className="eyebrow dark">REPOSITORY QUALITY</p><h2>Make the evidence structure repeatable.</h2><p>GitHub Actions validates required detection documentation, filename hygiene, incident/evidence structure and portfolio-lab disclosures. The quality workflow is green, giving reviewers evidence that the repository has repeatable controls rather than static screenshots alone.</p></section><section id="validation" className="case-section"><p className="eyebrow dark">VALIDATION STATUS</p><h2>Do not call simulated evidence complete until it exists.</h2><p>INC-001 is intentionally still open. The remaining evidence requires a controlled lab identity, six invalid-password attempts, the resulting DET-001 query result, a Sentinel incident and an investigation timeline from the authorised Azure tenant.</p><p>That evidence will complete the chain: <strong>controlled event → telemetry → KQL detection → Sentinel incident → investigation → analyst decision</strong>.</p></section><section id="lessons" className="case-section"><p className="eyebrow dark">LESSONS</p><h2>The strongest detection is one another analyst can understand, test and challenge.</h2><p>This project has evolved from a small KQL-and-screenshot lab into a documented security-engineering workflow. The next maturity step is real controlled validation, followed by tuning the threshold and adding stronger correlation logic rather than increasing rule count for appearance.</p></section></article></div></section></main></CaseStudyShell>;
}
